name: React App Pipeline

trigger:
  branches:
    include:
    - public-main
    - ado-pipeline
  # paths:
  #   include:
  #   - SinglePageApp/ClientApp/*

pr:
  - public-main
  - ado-pipeline


variables:
  sourceId: sourceCode_$(Build.BuildId)

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: Checkout
    displayName: 'Checkout out source'
    jobs:
    - job: 'Checkout'
      steps:
        - checkout: self

        - publish: $(Build.SourcesDirectory)
          displayName: 'Stash source'
          artifact: $(sourceId)

  - stage: QualityGates
    displayName: 'Quality Gates'
    jobs: 
    - job: Build
      displayName: 'Build'
      steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        displayName: 'Unstash source'
        inputs:
          artifact: $(sourceId)
          path: $(Build.SourcesDirectory)

      - task: NodeTool@0 
        inputs:
          versionSpec: '10.14.1'
        displayName: 'Install node'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm ci
        displayName: 'npm ci'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run build
        displayName: 'Build'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run test
        displayName: 'Test'
