name: React App Pipeline

trigger:
  branches:
    include:
    - public-main
    - ado-pipeline
  # paths:
  #   include:
  #   - SinglePageApp/ClientApp/*

pr:
  - public-main
  - ado-pipeline

pool:
  vmImage: 'windows-latest'

stages:
  - stage: QualityGates
    displayName: 'Quality Gates'
    jobs: 
    - job: Build
      displayName: 'Build'
      steps:

      - task: NodeTool@0 
        inputs:
          versionSpec: '10.14.1'
        displayName: 'Install node'

      - script: |
          cd ./SinglePageApp/ClientApp/
          npm install
        displayName: 'npm install'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run build
        displayName: 'Build'

- job: Test
      steps:
      displayName: 'Test'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run test
        displayName: 'Test'