name: React App Pipeline

trigger:
  branches:
    include:
    - public-main
    - ado-pipeline
  # paths:
  #   include:
  #   - SinglePageApp/ClientApp/*

pr:
  - public-main
  - ado-pipeline

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Checkout
    displayName: 'Checkout the code from repo'
    jobs: 
    - job: Checkout
      steps:
      - checkout: self

      - task: NodeTool@0 
        inputs:
          versionSpec: '10.14.1'
        displayName: 'Install node'

      - script: |
          cd ./SinglePageApp/ClientApp/
          npm install
        displayName: 'npm install'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run build
        displayName: 'Build'

      - bash: |
          cd ./SinglePageApp/ClientApp/
          npm run test
        displayName: 'Test'