name: React App Pipeline

trigger:
  branches:
    include:
    - public-main
    - ado-pipeline

pr: none

variables:
  source_id: sourceCode_$(Build.BuildId)
  build_artifact_name: build_$(Build.BuildId)

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: Checkout
    displayName: 'Checkout out source'
    jobs:
    - job: 'Checkout'
      steps:
        - checkout: self

        - publish: $(Build.SourcesDirectory)
          displayName: 'Stash source'
          artifact: $(source_id)

  - template: ./ci-stage.yml
    parameters:
      build_artifact_name: $(build_artifact_name)
      source_id: $(source_id)

  - template: ./cd-stage.yml
    parameters:
      build_artifact_name: $(build_artifact_name)
      source_id: $(source_id)
