

stages:
- stage: QualityGates
  displayName: 'Quality Gates'
  jobs: 

  - job: job1
    steps:
    - checkout: none

    - bash: |
        echo "##vso[task.setvariable variable=jimmyNoOutput]Jimmy 1"
      displayName: "assign no output"
      name: NoOutput

    - bash: |
        echo "##vso[task.setvariable variable=jimmyWithOutput;isOutput=true]Jimmy 2"
      displayName: "assign with output"
      name: WithOutput

    - bash: |
        echo $(System.JobId)
      displayName: Job Id

    # - bash: |
    #     echo "value $(jimmyNoOutput)"
    #   displayName: "Display 1"

    # - bash: |
    #     echo "value $(jimmyWithOutput)"
    #   displayName: "Display 2"

    # - bash: |
    #     echo "value $(NoOutput.jimmyNoOutput)"
    #   displayName: "Display 3"

    # - bash: |
    #     echo "value $(WithOutput.jimmyWithOutput)"
    #   displayName: "Display 4"

  - job: job2
    dependsOn: job1
    # variables:
    #   jimmyNoOutput: $[ dependencies.job1.outputs['test1.jimmyNoOutput'] ]
    #   jimmyWithOutput: $[ dependencies.job1.outputs['test2.jimmyWithOutput'] ]
    steps:

    - bash: |
        echo $(System.JobId)
      displayName: Job Id

    # - bash: |
    #     echo "jimmyWithOutput $(jimmyWithOutput)"