

stages:
- stage: QualityGates
  displayName: 'Quality Gates'
  jobs: 

  - job: job1
    steps:
    - checkout: none

    - bash: |
        echo "##vso[task.setvariable variable=jimmyNoOutput]Jimmy 1"
      displayName: "assign no output"
      name: test1

    - bash: |
        echo "##vso[task.setvariable variable=jimmyWithOutput;isOutput=true]Jimmy 2"
      displayName: "assign with output"
      name: test2

    - bash: |
        echo "value $(jimmyNoOutput)"
      displayName: "jimmyNoOutput"

    - bash: |
        echo "value $(jimmyWithOutput)"
      displayName: "jimmyWithOutput"

    - bash: |
        echo "value $(test1.jimmyNoOutput)"
      displayName: "test1.jimmyNoOutput"

    - bash: |
        echo "value $(test2.jimmyWithOutput)"
      displayName: "test2.jimmyWithOutput"

  - job: job2
    dependsOn: job1
    variables:
      jimmyNoOutput: $[ dependencies.job1.outputs['test1.jimmyNoOutput'] ]
      jimmyWithOutput: $[ dependencies.job1.outputs['test2.jimmyWithOutput'] ]
    steps:

    - bash: |
        echo "jimmyNoOutput $(jimmyNoOutput)"

    - bash: |
        echo "jimmyWithOutput $(jimmyWithOutput)"