

stages:
- stage: QualityGates
  displayName: 'Quality Gates'
  jobs: 

  - job: Jimmy
    steps:
    # Create a variable
    
    - bash: |
        echo $(System.JobId)
      displayName: "print job id"
    
    - bash: |
        echo "##vso[task.setvariable variable=sauce]$(System.JobId)"
      displayName: "assign job id"

    # Use the variable
    # "$(sauce)" is replaced by the contents of the `sauce` variable by Azure Pipelines
    # before handing the body of the script to the shell.
    - bash: |
        echo "job id $(sauce)"

  # - job: Build
  #   displayName: 'Build'
  #   steps:
  #   - checkout: none
